# Exercise 1

## Matrix and operations using Tensorflow



Define using the following matrices 

$$ A =
\begin{bmatrix}
1 & 2 & 1\\
3 & 1 & 2\\
1 & 1 & 1\\
\end{bmatrix}
$$

$$ B =
\begin{bmatrix}
2 & 2 & 1\\
3 & 2 & 1\\
1 & 2 & 2\\
\end{bmatrix}
$$

and perform the following calculations


In [1]:
# Import libraries
import tensorflow as tf
import numpy as np
tf.keras.backend.set_floatx('float64') # Removes TensorFlowin warnings considering the datatypes

In [2]:
#Write the answer in this cell and run
# Define matrixes using tf.Variable

a = tf.Variable([ [1, 2, 1], [3, 1, 2], [1, 1, 1] ])
b = tf.Variable([ [2, 2, 1], [3, 2, 1], [1, 2, 2] ])

print(a)
print(b)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 1],
       [3, 1, 2],
       [1, 1, 1]])>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[2, 2, 1],
       [3, 2, 1],
       [1, 2, 2]])>


In [3]:
#Write the answer in this cell and run
# Addition

addition = a + b
print(addition)

tf.Tensor(
[[3 4 2]
 [6 3 3]
 [2 3 3]], shape=(3, 3), dtype=int32)


In [4]:
#Write the answer in this cell and run
# Subtraction

substraction = a - b
print(substraction)

tf.Tensor(
[[-1  0  0]
 [ 0 -1  1]
 [ 0 -1 -1]], shape=(3, 3), dtype=int32)


In [5]:
#Write the answer in this cell and run
# Multiplication AB and BA

print(tf.matmul(a, b))
print(tf.matmul(b, a))

tf.Tensor(
[[ 9  8  5]
 [11 12  8]
 [ 6  6  4]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 9  7  7]
 [10  9  8]
 [ 9  6  7]], shape=(3, 3), dtype=int32)


How many addition and multiplication operations occurs when matrixes A and B are multiplied? 

There is 3 rows and 3 columns -> 9 new "cells". Each contains 3 multiplications and 2 additions. 9 x 3 = 27. 9 x 2 = 18.
Answer: 18 addition and 27 multiplication operations.

In [6]:
#Write the answer in this cell and run
# Transposition of A and B

print(tf.transpose(a))
print(tf.transpose(b))

tf.Tensor(
[[1 3 1]
 [2 1 1]
 [1 2 1]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[2 3 1]
 [2 2 2]
 [1 1 2]], shape=(3, 3), dtype=int32)


## Matrix and operations using Python (numpy)

Same matrixes as in Tensorflow exercises


In [7]:
#Write the answer in this cell and run
# Define matrixes using numpy


# Depracated! https://numpy.org/doc/stable/reference/generated/numpy.matrix.html -> use regular arrays instead

aa = np.array([[1, 2, 1], 
               [3, 1, 2], 
               [1, 1, 1]])
bb = np.array([[2, 2, 1],
               [3, 2, 1],
               [1, 2, 2]])

print(aa)
print(bb)

[[1 2 1]
 [3 1 2]
 [1 1 1]]
[[2 2 1]
 [3 2 1]
 [1 2 2]]


In [8]:
#Write the answer in this cell and run
# Addition

print(aa + bb)


[[3 4 2]
 [6 3 3]
 [2 3 3]]


In [9]:
#Write the answer in this cell and run
# Subtraction

print(aa - bb)

[[-1  0  0]
 [ 0 -1  1]
 [ 0 -1 -1]]


In [10]:
#Write the answer in this cell and run
# Multiplication AB and BA


print(np.dot(aa,bb))
print(np.dot(bb, aa))

# same
# print(aa @ bb)
# print(bb @ aa)
# https://www.geeksforgeeks.org/multiplication-two-matrices-single-line-using-numpy-python/

[[ 9  8  5]
 [11 12  8]
 [ 6  6  4]]
[[ 9  7  7]
 [10  9  8]
 [ 9  6  7]]


In [11]:
#Write the answer in this cell and run
# Transposition of A 

# pari tapaa
print(np.transpose(aa))
print(aa.T)

# pari lisää https://www.geeksforgeeks.org/transpose-matrix-single-line-python/

[[1 3 1]
 [2 1 1]
 [1 2 1]]
[[1 3 1]
 [2 1 1]
 [1 2 1]]


In [12]:
#Write the answer in this cell and run
# Determinant of A and B

print(np.linalg.det(aa))
print(np.linalg.det(bb))
# These are negative, so the orientation of space has been inverted (kind of flipped)
# The absolute value of determinant tells the factor by which the areas have been scaled
# see https://youtu.be/Ip3X9LOh2dk?t=251

# Inversion matrix of A and B, is possible


-1.0000000000000002
-2.0000000000000004


In [13]:
#Write the answer in this cell and run
# Check the A * A^t = I


## Keras

1. Use Keras Functional API to implement neural network (use Iris dataset): https://keras.io/guides/functional_api/   
2. Keras compilation parameters same as in Keras Sequential model example
3. Add neurons/nodes to hidden layer
4. Change epoch
5. Print the accuracy for each implementations
 

### Keras Functional API implementation

In [14]:
# Keras Function API implementation cell

import numpy as np
import pandas as pd
import seaborn as sns
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split

tf.keras.backend.set_floatx('float64') # changes all layers to have dtype float64 by default (matters when dense-layer is casting an input tensor from dtype float64 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  Without this change the layer has dtype float32 because its dtype defaults to floatx)

dataset = sns.load_dataset("iris") # downloads example dataset from the online reposity and returns df

#dataset.info()
#dataset


In [15]:
dataset['species'] = pd.Categorical(dataset['species']) 
dataset['species'] = dataset['species'].cat.codes

# no shuffle needed, as train_test_split will do it by default https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Y = dataset['species'] # output
X = dataset.drop(['species'], axis = 1) # input 

train_X, test_X, train_y, test_y = train_test_split(X, Y, test_size = 0.2, random_state = 42)

# Using from_tensor_slices -function convert Numpy-tables to TensorFlow's Dataset class
train_dataset = tf.data.Dataset.from_tensor_slices((train_X,train_y))
test_dataset = tf.data.Dataset.from_tensor_slices((test_X,test_y))

# Define the batch size
train_dataset,test_dataset = train_dataset.batch(1), test_dataset.batch(1)


In [16]:
print("Training Input shape\t: {}".format(train_X.shape))
print("Testing Input shape\t: {}".format(test_X.shape))
print("Training Output shape\t: {}".format(train_y.shape))
print("Testing Output shape\t: {}".format(test_y.shape))

Training Input shape	: (120, 4)
Testing Input shape	: (30, 4)
Training Output shape	: (120,)
Testing Output shape	: (30,)


In [17]:
# Add neurons/nodes to hidden layer

# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation = 'relu', input_shape = (4, )),
        layers.Dense(6, activation = 'relu'),
        layers.Dense(3, activation = 'softmax'),
    ]
)



In [18]:
# Keras compilation parameters same as in Keras Sequential model example

model.compile(loss='sparse_categorical_crossentropy', # Loss
              optimizer='adam', # Adam optimizer with default parameters
              metrics=['accuracy'] # Accuracy is used in classification problems. 
             )

In [19]:
model.fit(train_dataset, 
          epochs=50)

# Print the model
model.summary()

Epoch 1/50
120/120 [==============================] - 0s 627us/step - loss: 1.0299 - accuracy: 0.6250
Epoch 2/50
120/120 [==============================] - 0s 581us/step - loss: 0.9938 - accuracy: 0.3583
Epoch 3/50
120/120 [==============================] - 0s 597us/step - loss: 0.9602 - accuracy: 0.3833
Epoch 4/50
120/120 [==============================] - 0s 654us/step - loss: 0.9268 - accuracy: 0.3833
Epoch 5/50
120/120 [==============================] - 0s 628us/step - loss: 0.8933 - accuracy: 0.3833
Epoch 6/50
120/120 [==============================] - 0s 597us/step - loss: 0.8595 - accuracy: 0.4083
Epoch 7/50
120/120 [==============================] - 0s 586us/step - loss: 0.8253 - accuracy: 0.4167
Epoch 8/50
120/120 [==============================] - 0s 606us/step - loss: 0.7906 - accuracy: 0.4417
Epoch 9/50
120/120 [==============================] - 0s 586us/step - loss: 0.7561 - accuracy: 0.7500
Epoch 10/50
120/120 [==============================] - 0s 613us/step - loss: 0.722

In [20]:
results = model.evaluate(test_dataset)
print(results)
print(f"Accuracy in percents: {results[1]*100:.0f}%")

30/30 [==============================] - 0s 1ms/step - loss: 0.1772 - accuracy: 0.9667
[0.17724143130083878, 0.9666666666666667]
Accuracy in percents: 97%


In [21]:
# Talteen

# https://stackoverflow.com/questions/44747343/keras-input-explanation-input-shape-units-batch-size-dim-etc
# https://datascience.stackexchange.com/questions/53609/how-to-determine-input-shape-in-keras
# https://towardsdatascience.com/how-to-use-dataset-in-tensorflow-c758ef9e4428
    
# https://www.kaggle.com/code/rushabhwadkar/deep-learning-with-keras-on-iris-dataset/notebook
# https://medium.com/@nutanbhogendrasharma/tensorflow-deep-learning-model-with-iris-dataset-8ec344c49f91 
    
# https://towardsdatascience.com/train-your-neurons-on-artificial-neural-networks-featuring-keras-2757f51bb7ed
    
# https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html
    
